services:
  - type: web
    name: sapp-java-api
    rootDir: scheduling-app-backend
    buildCommand: ./mvnw package -DskipTests
    startCommand: java -jar target/scheduling-app-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: sched database
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        value: sappdb_user
      - key: SPRING_DATASOURCE_PASSWORD
      - key: JWT_SECRET
      - key: JWT_EXPIRATION
        value: 86400000
