spring.datasource.url=jdbc:postgresql://localhost:5432/scheduling_app
spring.datasource.username= HIDDEN USERNAME
spring.datasource.password= HIDDEN PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
